### PR TITLE
Fix missing expectation in map not causing test failures

### LINKED ISSUE #117: Expected headers are ignored
The matched headers are iterated over the `actual` headers instead of the `expected` headers here: https://github.com/lomsa-dev/http-mock-adapter/blob/main/lib/src/extensions/matches_request.dart#L75

This means, that expectations are just ignored if they are not actually present. This seems wrong. Same goes for query parameters and others things that are matched via `Map`.

### PR DESCRIPTION
**Pull request by kuhnroyal**
## Description

Fixes #117 and now causes unmatched expectations in header/query-params (everything that is matched via a map) to cause test failures. Previously they were just ignored.

Additionally this change gives the adapter/interceptor access to the `BaseOptions` in order to access default values which allows easy reuse of existing `Dio` instances and their configuration.

Also removed a lot of unused code in request matchers/handlers.

### CODE REVIEW

**Review by theiskaa — APPROVED** [review]
**Everything is ok for me, Thanks for the PR!**

**Review by GiorgiBeriashvili — CHANGES_REQUESTED** [review]
Looks good to me, thank you for your work!

I added a suggestion to raise test coverage to 100% just for the sake of it, though it's just superficial. By trying edit tests for aforementioned reason, I noticed some difference between an adapter and an interceptor, namely how an adapter adds `content-length` automatically to the request headers, where an interceptors requires manual assignment. It is unrelated to your changes but it's good to know as it could be modified later to mock both cases in a similar way.

Relatedly, code base could also use some refactoring later for developer experience based on your changes, since it's `MockServer server` instead of `request` now, and `dart` automatically fills in the `server` instead of now-old `request`, rendering existing documentation/tests a bit outdated in a sense.

**Comment by kuhnroyal** [comment]
I added some further changes since I noticed due to @GiorgiBeriashvili's comment, that there was still a problem with some headers being added automatically and some not. I mainly created a central place where request headers are added, which are usually added by default by Dio.
Also the `onRoute` implementation is now the same for both `DioAdapter` and `DioInterceptor` - this simplifies things a lot.

* improve construction of `DioAdapter` and `DioInterceptor` and pass the full `Dio` instance - this additionally allows access to the configured `transformer`
* configure default headers in one place in `RequestHandling` which are usually set by `DioMixin`
* move `onRoute` implementation to `RequestHandling` as it is now the same for adapter and interceptor
* simplify `MatchesRequest` implementation
* apply new naming to tests, example and README

Again there are no changes to test logic which should mean that there is no change in behavior.

File: test/interceptors/dio_interceptor_test.dart [hunk 1]
```diff
@@ -135,10 +132,6 @@ void main() {
     });
 
     test('mocks multiple requests sequentially by method chaining', () async {
```
[the remark this answers is not in the document]
Comment (kuhnroyal) [reply test/interceptors/dio_interceptor_test.dart:134]: I don't think manually adding headers to the request is good. Default headers are now added automatically as soon as there is some data in POST/PUT/DELETE/PATCH request. So I just added some data to the requests here. Will see where this leads to with the coverage.

File: lib/src/mixins/request_handling.dart [hunk 2]
```diff
@@ -1,23 +1,95 @@
...
+  /// * content-length
+  Future<void> setDefaultRequestHeaders(Dio dio, RequestOptions options) async {
+    final data = options.data;
+    if (data != null &&
+        RequestMethods.allowedPayloadMethods
+            .contains(RequestMethods.forName(name: options.method))) {
+      if (data is FormData) {
+        options.headers[Headers.contentTypeHeader] =
+            'multipart/form-data; boundary=${data.boundary}';
+        options.headers[Headers.contentLengthHeader] = data.length.toString();
```
Comment (kuhnroyal) [inline lib/src/mixins/request_handling.dart:28]: Need to test this FormData default handling

File: lib/src/mixins/request_handling.dart [hunk 3]
```diff
@@ -1,23 +1,95 @@
...
+      } else {
+        final _data = await dio.transformer.transformRequest(options);
+        List<int> bytes;
+        if (options.requestEncoder != null) {
+          bytes = options.requestEncoder!(_data, options);
+        } else {
+          bytes = utf8.encode(_data);
```
Comment (kuhnroyal) [inline lib/src/mixins/request_handling.dart:35]: Not covered

File: lib/src/mixins/request_handling.dart [hunk 4]
```diff
@@ -1,23 +1,95 @@
...
+        }
+        options.headers[Headers.contentLengthHeader] = bytes.length.toString();
+        options.headers.putIfAbsent(
+          Headers.contentTypeHeader,
+          () => Headers.jsonContentType,
```
Comment (kuhnroyal) [inline lib/src/mixins/request_handling.dart:40]: I think the json content header is not set in `DioMixin` but in `Options.compose` so it is in all cases already configured here. This can probably be removed.

**Comment by kuhnroyal** [comment]
Coverage is 100% now. Since most of the behavior is now in `RequestHandling`, we can probably run the exact same test suit against `DioAdapter` and `DioInterceptor` but this should be done in a separate PR.

**Comment by kuhnroyal** [comment]
After looking at #111 I think we should no longer add any default matchers on headers. This was needed because when matching the headers the code iterated over the actual headers and not the expectations (see #117). This is no longer the case, so we don't need the default matchers, this would make everything lot more transparent and prevent issues like in #111.

I will prepare this also in a separate PR once this one is merged.

**Review by GiorgiBeriashvili — APPROVED** [review]
> After looking at #111 I think we should no longer add any default matchers on headers. This was needed because when matching the headers the code iterated over the actual headers and not the expectations (see #117). This is no longer the case, so we don't need the default matchers, this would make everything lot more transparent and prevent issues like in #111.
> 
> I will prepare this also in a separate PR once this one is merged.

Agreed. Everything is more than acceptable for me.

**Review by theiskaa — APPROVED** [review]
**Approved! (again :D)** 

Thanks for contributing!

**Comment by kuhnroyal** [comment]
Would be great if you guys can cut a release with this. Kinda need this in https://github.com/OpenAPITools/openapi-generator/pull/9975 :)

**Comment by GiorgiBeriashvili** [comment]
> Would be great if you guys can cut a release with this. Kinda need this in [OpenAPITools/openapi-generator#9975](https://github.com/OpenAPITools/openapi-generator/pull/9975) :)

It's live now, sorry for the delay.
